# Generated by Django 4.0.3 on 2022-03-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tider', '0002_subreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
