# Generated by Django 4.0.3 on 2022-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tider', '0003_subreddit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
